### ISSUE TITLE
Support Live Preview

### ISSUE THREAD

**Issue by NomarCub** [superDuperCyberTechno/obsidian-code-copy#9]
The new live preview mode doesn't have code copy buttons. There's a built in copy button now, but that also doesn't work in live preview.

**Comment by superDuperCyberTechno** [comment]
Seeing as Obsidian has this built-in now, I'm gonna close the repo.

I am sorry if this is something you'd rely on but I simply don't have the time to make this work. I suggest you aim your request at the Obsidian devs.

**Comment by Cito** [comment]
Right, it's built-in in live preview since 0.13.18, so this plug-in is actually not needed any more. I suggest to [archive](https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories) this repo, not to delete it.
